USE DUMMY ;
SELECT * FROM STUDENTINFO;
SELECT * FROM STUDENTINFO WHERE DEPARTMENT = "IT";
SELECT AVG(SALARY) FROM STUDENTINFO GROUP BY DEPARTMENT HAVING AVG(SALARY) < 60000; 
SELECT AVG(SALARY) , department FROM STUDENTINFO GROUP BY DEPARTMENT HAVING AVG(SALARY)  > 55000 OR COUNT(*) > 1