CREATE TABLE STUDENTINFO (
EmployeeID INT,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Department VARCHAR(50),
Salary INT
);

INSERT INTO STUDENTINFO (EmployeeID, FirstName, LastName, Department, Salary)
VALUES
(1, 'John', 'Doe', 'HR', 55000),
(2, 'Jane', 'Smith', 'IT', 60000),
(3, 'Bob', 'Johnson', 'IT', 62000),
(4, 'Alice', 'Williams', 'HR', 54000),
(5, 'Eva', 'Davis', 'Finance', 58000),
(6, 'Mike', 'Brown', 'Finance', 59000);



SELECT * FROM STUDENTINFO ORDER BY LASTNAME ASC ;

SELECT * FROM STUDENTINFO WHERE DEPARTMENT = "IT" ORDER BY SALARY DESC;

SELECT COUNT(*)  AS TOTALMEMBERS , DEPARTMENT FROM STUDENTINFO GROUP BY DEPARTMENT;

SELECT AVG(SALARY) AS AVERAGESALARY , DEPARTMENT FROM STUDENTINFO GROUP BY DEPARTMENT ORDER BY DEPARTMENT ASC


